---

  - name: "APT - install 'nginx'"
    apt:
      name: "nginx"
      update_cache: yes

  - name: "Copy nginx config from template"
    copy:
      src: tmp/nginx/
      dest: /etc/nginx/

  - name: insert line in file
    shell: echo "
                  fs.inotify.max_user_watches=1048576\n
                  fs.file-max=2097152\n
                  vm.max_map_count=262144\n
                  net.core.somaxconn=1024\n
                  net.core.netdev_max_backlog=2000\n
                  net.ipv4.tcp_max_syn_backlog=2048\n
                  " >> /etc/sysctl.conf

  - name: Restart nginx, in all cases
    service:
      name: nginx
      state: restarted

  - name: "Configuration sysctl"
    shell: sysctl --system